disabled_rules:
  - opening_brace

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - compiler_protocol_init
  - custom_rules
  - discouraged_optional_boolean
  - discouraged_object_literal
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - vertical_whitespace_opening_braces

force_cast: warning
force_unwrapping: warning
force_try: warning

function_body_length:
  warning: 100

line_length: 120

file_length:
  warning: 800

closure_body_length:
  warning: 20

type_name:
  min_length: 1

identifier_name:
  min_length: 1

large_tuple:
  warning: 5
  
function_parameter_count:
  warning: 8
  
cyclomatic_complexity:
  warning: 10
  
nesting:
  type_level:
    warning: 5

warning_threshold: 1

reporter: "xcode"
